spring:
  profiles:
    active: dev
    
---
server:
  port: 8002

spring:
  profiles: dev
    application:
    name: microservicecloud-dept
  

---

server:
  port: 8003

spring:
  profiles: test
    application:
    name: microservicecloud-dept
  
